/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: sc8di (https://sketchfab.com/sc8di)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sphericon-pendant-05a736d27b91452387d451bc9a796b23
Title: Sphericon Pendant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Cylinder002__0.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Cylinder002__0_1.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Cylinder002__0_2.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Cylinder002__0_3.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Cylinder002__0_4.geometry} material={materials['Scene_-_Root']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
